### ISSUE TITLE
Update the DUHacks 3.0 Website

### ISSUE THREAD

**Issue by 0xvashishth** [developer-student-clubs/duhacks#14]
Hi @kunjgit  @patelhitarth08  @rajatnai49 

Please update the duhacks website code here with a new branch as `duhacks3.0`

**Do not directly push into the repo, create a pull request for the same.**

Let me know if you need any help.

**Comment by kunjgit** [comment]
@0xvashishth sure !

**Comment by 0xvashishth** [comment]
You can still, make a PR if there will be any major change.
The same should be done for 4.0. so You just inform the future Lead Org.

We will miss our DUHacks Era 💯
